baseURL: "https://justinz2018.github.io"
languageCode: "en-us"
title: "Justin Zhang - Personal Website"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1

params:
  title: "Justin Zhang"
  description: Justin Zhang's personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Justin."
    subtitle: "I'm a software engineer"
    content: "A software developer who specializes in systems programming, data engineering, and finance."
    image: /images/hero.jpeg
    button:
      enable: true
      name: "Resume"
      url: "https://raw.githubusercontent.com/justinz2018/justinz2018.github.io/main/static/resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/justinz2018/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/justin-zhang-345725190/
          #customIcons:
          #  - icon: /fav.png
          #    url: "#"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a software developer with a passion for systems programming and data engineering.
      I have a background in computer science and finance, and have a particular interest in the intersection of the two fields.
      I will be working full-time as a software developer at [Citadel](https://www.citadel.com/) in New York starting in August 2022.

      I am currently working on wrapping up my undergraduate studies at Caltech. In my spare time, I enjoy running and being in nature.
    skills:
      enable: true
      title: "Here are the technologies I'm most familiar with:"
      items:
        - "C/C++"
        - "Python"
        - "Java"
        - "JavaScript"
        - "NumPy, pandas, Matplotlib"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineering Intern"
        company: "DRW"
        companyUrl: "https://drw.com/"
        date: "June 2021 - August 2021"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: "At DRW, I sought to lessen the time spent traders spent manually quoting prices. To this end, I created an auto-responder for quote requests from other brokers and integrated the tool into DRW's trading platform. The major technologies I used include Java and protobuf."

      - job: "Software Engineering Intern"
        company: "Citadel"
        companyUrl: "https://www.citadel.com/"
        date: "February 2021 - April 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: .
        content: |
          My team at Citadel focused on creating and maintaining technologies to support electronic trading. In support of this, I worked on two main projects.
          - I added additional querying features for Citadel's existing marketdata API (C++).
          - I performed data analysis on market data to allow migration to a newer marketdata pipeline (kdb, Python, pandas).

      - job: "Web Development Intern"
        company: "Asana"
        companyUrl: "https://asana.com/"
        date: "June 2020 - September 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Asana is a web-based work management application. To help users track milestones and deadlines, I helped to create JavaScript-based data visualizations that users could see in one centralized dashboard. This ultimately allowed users to better understand their progress at a glance. The main technologies used were Elasticsearch, Scala, and React.

      - job: "Data Engineering Intern"
        company: "Robinhood"
        companyUrl: "https://robinhood.com/"
        date: "June 2019 - September 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Robinhood allows their users to trade options, a highly leveraged financial instrument. To help with risk management, I designed a model to detect high-risk options positions based on the well-known binomial options pricing model. The main technologies used were Spark, Kafka, Airflow, and Presto.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "B.Sc. in Computer Science and Business, Economics, Management"
        school:
          name: "Caltech"
          url: "https://www.caltech.edu/"
        date: "2018 - 2022"
        GPA: "4.1 out of 4.3"
        content: |-
            TA positions
            - CS 124 (Operating Systems)

            Extracurricular Activities
            - Student Investment Fund (SIF)
            - Quant finance club
            - Chess club


        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: ICPC Southern California Regionals
        content: My team received first place in the ICPC regionals programming contest, competing against other top schools in the southern California area.
        url: http://socalcontest.org/current/index.shtml
      - title: USA Computing Olympiad (USACO)
        content: I was a national finalist and camp qualifier for USACO, awarded to fewer than 30 students nationwide every year.
        url: http://usaco.org/
      - title: Facebook Hacker Cup
        content: I was a top 2000 contestant in Facebook Hacker Cup, a worldwide online programming competition.
        url: https://www.facebook.com/codingcompetitions/hacker-cup

  # projects
  projects:
    enable: true
    items:
      - title: Unflixable
        content: |
          ^Image: Testing our model for Bartow County, GA. From project final report^\
          This was a project to predict the number of Coronavirus cases in spring of 2020, done for Caltech's CS 156b class. Our model was a hierarchical logistic growth model, trained with MCMC methods. From the model, we were able to gain some insight into how public policy had affected COVID case counts.
        image: /images/unflixable.png

      - title: GL-renderer
        content: |
          ^Image: Four cubes shaded in GL-renderer with Gouraud shading^\
          GL-renderer was a project to render various objects from their object file specifications, done for Caltech's CS 171 class in the fall of 2019. Supported shading modes included Gouraud and Phong, as well as basic support for ray tracing.
        image: /images/gl_renderer.png

  #Contact
  contact:
    enable: true
    content: My inbox is always open. If you have any questions, please feel free to reach out!
    email: jrzhang@caltech.edu
    btnName: Contact me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/justinz2018/
      linkedin: https://www.linkedin.com/in/justin-zhang-345725190/
