baseURL: "https://justinz2018.github.io"
languageCode: "en-us"
title: "Justin Zhang - Personal Website"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1

params:
  title: "Justin Zhang"
  description: Justin Zhang's personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Justin."
    subtitle: "I'm a software engineer"
    content: "A software developer who specializes in systems programming, data engineering, and finance."
    image: /images/hero.jpeg
    button:
      enable: true
      name: "Resume"
      url: "https://raw.githubusercontent.com/justinz2018/justinz2018.github.io/main/static/resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/justinz2018/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/justin-zhang-345725190/
          #customIcons:
          #  - icon: /fav.png
          #    url: "#"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a software developer with a passion for systems programming and data engineering. I have a background in computer science and finance, and have a particular interest in the intersection of the two fields. I will be working full-time as a software developer at [Citadel](https://www.citadel.com/) in New York starting in August 2022.

      I am currently working on wrapping up my undergraduate studies at Caltech.
    skills:
      enable: true
      title: "Here are the technologies I'm most familiar with:"
      items:
        - "C/C++"
        - "Python"
        - "Java"
        - "JavaScript"
        - "NumPy, pandas, Matplotlib"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineering Intern"
        company: "DRW"
        companyUrl: "https://drw.com/"
        date: "June 2021 - August 2021"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: "At DRW, I worked on creating an auto-responder for quote requests from other brokers, as part of DRW's trading platform. Technologies used include Java and protobuf."

      - job: "Software Engineering Intern"
        company: "Citadel"
        companyUrl: "https://www.citadel.com/"
        date: "February 2021 - April 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: .
        content: |
          At Citadel, I worked on two main projects.
          - I added additional querying features for Citadel's marketdata API (C++).
          - I performed data analysis on market data to allow migration to a newer marketdata pipeline (kdb, Python, pandas).

      - job: "Web Development Intern"
        company: "Asana"
        companyUrl: "https://asana.com/"
        date: "June 2020 - September 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I worked to create web-based data visualizations to allow users to better analyze their usage data. Technologies used include Elasticsearch, Scala, and React.

      - job: "Data Engineering Intern"
        company: "Robinhood"
        companyUrl: "https://robinhood.com/"
        date: "June 2019 - September 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I designed a model to detect high-risk options positions, based on the well-known binomial options pricing model. Technologies used include Spark, Kafka, Airflow, and Presto.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "B.Sc. in Computer Science and Business, Economics, Management"
        school:
          name: "Caltech"
          url: "https://www.caltech.edu/"
        date: "2018 - 2022"
        GPA: "4.1 out of 4.3"
        content: |-
            TA positions
            - CS 124 (Operating Systems)

            Extracurricular Activities
            - Student Investment Fund (SIF)
            - Quant finance club
            - Chess club


        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: ICPC Southern California Regionals
        content: My team received first place in the ICPC regionals programming contest, competing against other top schools in the southern California area.
        url: http://socalcontest.org/current/index.shtml
      - title: USA Computing Olympiad (USACO)
        content: I was a national finalist and camp qualifier for USACO, awarded to fewer than 30 students nationwide every year.
        url: http://usaco.org/
      - title: Facebook Hacker Cup
        content: I was a top 2000 contestant in Facebook Hacker Cup, a worldwide online programming competition.
        url: https://www.facebook.com/codingcompetitions/hacker-cup

  # projects
  projects:
    enable: false
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://example.com
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://example.com

  #Contact
  contact:
    enable: true
    content: My inbox is always open. If you have any questions, please feel free to reach out!
    email: jrzhang@caltech.edu
    btnName: Contact me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/justinz2018/
      linkedin: https://www.linkedin.com/in/justin-zhang-345725190/
